The baseline CNN performed better on UNSW-NB15 than NSL-KDD. On UNSW-NB15, it achieved 92.23% accuracy and 94.18% F1-score, while on NSL-KDD it achieved 76.61% accuracy and 74.94% F1-score. Both models had high precision, but the NSL-KDD model had lower recall, meaning it missed more attack samples. The baseline model sizes were small, approximately 0.489 MB for NSL-KDD and 0.536 MB for UNSW-NB15, which makes them suitable starting points for lightweight optimization.

In [4]:
summary_columns = [
    "Dataset",
    "Model",
    "Accuracy",
    "Precision",
    "Recall",
    "F1-score",
    "Training Time Seconds",
    "Inference Time Seconds",
    "Model Size MB"
]

baseline_summary = baseline_comparison[summary_columns].copy()

for col in ["Accuracy", "Precision", "Recall", "F1-score"]:
    baseline_summary[col] = (baseline_summary[col] * 100).round(2)

baseline_summary["Training Time Seconds"] = baseline_summary["Training Time Seconds"].round(2)
baseline_summary["Inference Time Seconds"] = baseline_summary["Inference Time Seconds"].round(2)
baseline_summary["Model Size MB"] = baseline_summary["Model Size MB"].round(3)

baseline_summary

,Dataset,Model,Accuracy,Precision,Recall,F1-score,Training Time Seconds,Inference Time Seconds,Model Size MB
0,NSL-KDD,Baseline CNN,76.61,96.02,61.45,74.94,137.07,2.75,0.489
1,UNSW-NB15,Baseline CNN,92.23,96.10,92.33,94.18,43.73,14.66,0.536

In [3]:
baseline_comparison.to_csv(BASELINE_COMPARISON_PATH, index=False)

print("Baseline comparison saved to:", BASELINE_COMPARISON_PATH)
baseline_comparison

Baseline comparison saved to: C:\Users\Admin\Desktop\Lightweight-IoT-IDS\results\baseline_cnn_comparison.csv

,Dataset,Model,Accuracy,Precision,Recall,F1-score,Training Time Seconds,Inference Time Seconds,Model Size MB
0,NSL-KDD,Baseline CNN,0.766057,0.960185,0.614509,0.749406,137.072274,2.750228,0.488823
1,UNSW-NB15,Baseline CNN,0.922289,0.961005,0.923287,0.941769,43.730621,14.660965,0.535698

In [2]:
nslkdd_results = pd.read_csv(NSLKDD_RESULTS_PATH)
unsw_results = pd.read_csv(UNSW_RESULTS_PATH)

baseline_comparison = pd.concat(
    [nslkdd_results, unsw_results],
    ignore_index=True
)

baseline_comparison

,Dataset,Model,Accuracy,Precision,Recall,F1-score,Training Time Seconds,Inference Time Seconds,Model Size MB
0,NSL-KDD,Baseline CNN,0.766057,0.960185,0.614509,0.749406,137.072274,2.750228,0.488823
1,UNSW-NB15,Baseline CNN,0.922289,0.961005,0.923287,0.941769,43.730621,14.660965,0.535698

In [1]:
from pathlib import Path
import pandas as pd

PROJECT_ROOT = Path("..").resolve()
RESULTS_DIR = PROJECT_ROOT / "results"

NSLKDD_RESULTS_PATH = RESULTS_DIR / "nslkdd_cnn_baseline_results.csv"
UNSW_RESULTS_PATH = RESULTS_DIR / "unsw_cnn_baseline_results.csv"

BASELINE_COMPARISON_PATH = RESULTS_DIR / "baseline_cnn_comparison.csv"

print("NSL-KDD results exist:", NSLKDD_RESULTS_PATH.exists())
print("UNSW-NB15 results exist:", UNSW_RESULTS_PATH.exists())

NSL-KDD results exist: True
UNSW-NB15 results exist: True